/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppAppDashboardRouteImport } from './routes/_app.app.dashboard'
import { Route as AppAppStudentsIndexRouteImport } from './routes/_app.app.students.index'
import { Route as AppAppCasesIndexRouteImport } from './routes/_app.app.cases.index'
import { Route as AppAppStudentsNewRouteImport } from './routes/_app.app.students.new'
import { Route as AppAppStudentsIdRouteImport } from './routes/_app.app.students.$id'
import { Route as AppAppCasesNewRouteImport } from './routes/_app.app.cases.new'
import { Route as AppAppCasesIdRouteImport } from './routes/_app.app.cases.$id'
import { Route as AppAppStudentsIdEditRouteImport } from './routes/_app.app.students.$id.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppDashboardRoute = AppAppDashboardRouteImport.update({
  id: '/app/dashboard',
  path: '/app/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAppStudentsIndexRoute = AppAppStudentsIndexRouteImport.update({
  id: '/app/students/',
  path: '/app/students/',
  getParentRoute: () => AppRoute,
} as any)
const AppAppCasesIndexRoute = AppAppCasesIndexRouteImport.update({
  id: '/app/cases/',
  path: '/app/cases/',
  getParentRoute: () => AppRoute,
} as any)
const AppAppStudentsNewRoute = AppAppStudentsNewRouteImport.update({
  id: '/app/students/new',
  path: '/app/students/new',
  getParentRoute: () => AppRoute,
} as any)
const AppAppStudentsIdRoute = AppAppStudentsIdRouteImport.update({
  id: '/app/students/$id',
  path: '/app/students/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAppCasesNewRoute = AppAppCasesNewRouteImport.update({
  id: '/app/cases/new',
  path: '/app/cases/new',
  getParentRoute: () => AppRoute,
} as any)
const AppAppCasesIdRoute = AppAppCasesIdRouteImport.update({
  id: '/app/cases/$id',
  path: '/app/cases/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAppStudentsIdEditRoute = AppAppStudentsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppAppStudentsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/dashboard': typeof AppAppDashboardRoute
  '/app/cases/$id': typeof AppAppCasesIdRoute
  '/app/cases/new': typeof AppAppCasesNewRoute
  '/app/students/$id': typeof AppAppStudentsIdRouteWithChildren
  '/app/students/new': typeof AppAppStudentsNewRoute
  '/app/cases/': typeof AppAppCasesIndexRoute
  '/app/students/': typeof AppAppStudentsIndexRoute
  '/app/students/$id/edit': typeof AppAppStudentsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/dashboard': typeof AppAppDashboardRoute
  '/app/cases/$id': typeof AppAppCasesIdRoute
  '/app/cases/new': typeof AppAppCasesNewRoute
  '/app/students/$id': typeof AppAppStudentsIdRouteWithChildren
  '/app/students/new': typeof AppAppStudentsNewRoute
  '/app/cases': typeof AppAppCasesIndexRoute
  '/app/students': typeof AppAppStudentsIndexRoute
  '/app/students/$id/edit': typeof AppAppStudentsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/app/dashboard': typeof AppAppDashboardRoute
  '/_app/app/cases/$id': typeof AppAppCasesIdRoute
  '/_app/app/cases/new': typeof AppAppCasesNewRoute
  '/_app/app/students/$id': typeof AppAppStudentsIdRouteWithChildren
  '/_app/app/students/new': typeof AppAppStudentsNewRoute
  '/_app/app/cases/': typeof AppAppCasesIndexRoute
  '/_app/app/students/': typeof AppAppStudentsIndexRoute
  '/_app/app/students/$id/edit': typeof AppAppStudentsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/app/dashboard'
    | '/app/cases/$id'
    | '/app/cases/new'
    | '/app/students/$id'
    | '/app/students/new'
    | '/app/cases/'
    | '/app/students/'
    | '/app/students/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/dashboard'
    | '/app/cases/$id'
    | '/app/cases/new'
    | '/app/students/$id'
    | '/app/students/new'
    | '/app/cases'
    | '/app/students'
    | '/app/students/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/app/dashboard'
    | '/_app/app/cases/$id'
    | '/_app/app/cases/new'
    | '/_app/app/students/$id'
    | '/_app/app/students/new'
    | '/_app/app/cases/'
    | '/_app/app/students/'
    | '/_app/app/students/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/app/dashboard': {
      id: '/_app/app/dashboard'
      path: '/app/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppAppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/students/': {
      id: '/_app/app/students/'
      path: '/app/students'
      fullPath: '/app/students/'
      preLoaderRoute: typeof AppAppStudentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/cases/': {
      id: '/_app/app/cases/'
      path: '/app/cases'
      fullPath: '/app/cases/'
      preLoaderRoute: typeof AppAppCasesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/students/new': {
      id: '/_app/app/students/new'
      path: '/app/students/new'
      fullPath: '/app/students/new'
      preLoaderRoute: typeof AppAppStudentsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/students/$id': {
      id: '/_app/app/students/$id'
      path: '/app/students/$id'
      fullPath: '/app/students/$id'
      preLoaderRoute: typeof AppAppStudentsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/cases/new': {
      id: '/_app/app/cases/new'
      path: '/app/cases/new'
      fullPath: '/app/cases/new'
      preLoaderRoute: typeof AppAppCasesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/cases/$id': {
      id: '/_app/app/cases/$id'
      path: '/app/cases/$id'
      fullPath: '/app/cases/$id'
      preLoaderRoute: typeof AppAppCasesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/students/$id/edit': {
      id: '/_app/app/students/$id/edit'
      path: '/edit'
      fullPath: '/app/students/$id/edit'
      preLoaderRoute: typeof AppAppStudentsIdEditRouteImport
      parentRoute: typeof AppAppStudentsIdRoute
    }
  }
}

interface AppAppStudentsIdRouteChildren {
  AppAppStudentsIdEditRoute: typeof AppAppStudentsIdEditRoute
}

const AppAppStudentsIdRouteChildren: AppAppStudentsIdRouteChildren = {
  AppAppStudentsIdEditRoute: AppAppStudentsIdEditRoute,
}

const AppAppStudentsIdRouteWithChildren =
  AppAppStudentsIdRoute._addFileChildren(AppAppStudentsIdRouteChildren)

interface AppRouteChildren {
  AppAppDashboardRoute: typeof AppAppDashboardRoute
  AppAppCasesIdRoute: typeof AppAppCasesIdRoute
  AppAppCasesNewRoute: typeof AppAppCasesNewRoute
  AppAppStudentsIdRoute: typeof AppAppStudentsIdRouteWithChildren
  AppAppStudentsNewRoute: typeof AppAppStudentsNewRoute
  AppAppCasesIndexRoute: typeof AppAppCasesIndexRoute
  AppAppStudentsIndexRoute: typeof AppAppStudentsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAppDashboardRoute: AppAppDashboardRoute,
  AppAppCasesIdRoute: AppAppCasesIdRoute,
  AppAppCasesNewRoute: AppAppCasesNewRoute,
  AppAppStudentsIdRoute: AppAppStudentsIdRouteWithChildren,
  AppAppStudentsNewRoute: AppAppStudentsNewRoute,
  AppAppCasesIndexRoute: AppAppCasesIndexRoute,
  AppAppStudentsIndexRoute: AppAppStudentsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
